services:
  mysql:
    image: mysql:8.0
    container_name: portfolio-mysql
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect="SET NAMES utf8mb4"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: portfolio-phpmyadmin
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${DB_PASS}
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  mysql_data: 