name: Deploy to Atthost

on:
  push:
    branches:
      - release_build

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Set up SSH key
        run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
            chmod 400 ~/.ssh/id_rsa
            ssh-keyscan -p 6022 arturszwagrzak.atthost24.pl >> ~/.ssh/known_hosts

      - name: Clear cache and install dependencies
        run: rm -rf node_modules

      - name: Install dependencies
        run: npm install

      - name: Build Tailwind CSS
        run: npm run build:css

      - name: Build React app
        run: npm run build
        env:
          REACT_APP_API_BASE_URL: http://localhost:3001

      - name: Deploy to Atthost
        run: |
          chmod +x deploy.sh
          ./deploy.sh
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
