name: Deploy to Hosting

on:
  push:
    branches:
      - release_build

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: |
          npm cache clean --force
          npm ci --no-audit || npm install --no-audit

      - name: Run linting
        run: npm run lint

      - name: Type check
        run: npm run type-check

      - name: Run tests
        run: npm run test:coverage

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Set up SSH key
        run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
            chmod 400 ~/.ssh/id_rsa
            ssh-keyscan -H dm77338.domenomania.eu >> ~/.ssh/known_hosts
            eval "$(ssh-agent -s)"
            ssh-add ~/.ssh/id_rsa
            echo "SSH agent started and key added"
            
            # Debug: sprawdź fingerprint klucza
            echo "Private key fingerprint:"
            ssh-keygen -lf ~/.ssh/id_rsa
            
            # Test SSH connection
            echo "Testing SSH connection..."
            ssh -o ConnectTimeout=10 dm77338@dm77338.domenomania.eu "echo 'SSH connection successful'"
            
            # Jeśli nie działa, spróbuj z verbose
            echo "Trying with verbose output..."
            ssh -v -o ConnectTimeout=10 dm77338@dm77338.domenomania.eu "echo 'SSH connection successful'"
            

      - name: Clear cache and install dependencies
        run: rm -rf node_modules

      - name: Install dependencies
        run: |
          npm cache clean --force
          npm ci --no-audit || npm install --no-audit

      - name: Build Tailwind CSS
        run: npm run build:css

      - name: Build React app
        run: npm run build
        env:
          REACT_APP_API_BASE_URL: https://server.szwagrzak.pl/api

      - name: Deploy to Hosting
        run: |
          chmod +x deploy.sh
          ./deploy.sh
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_AUTH_SOCK: $SSH_AUTH_SOCK
